### ISSUE TITLE
Serious with the support?

### ISSUE THREAD

**Issue by vsobotka** [chriscamicas/vscode-abl#1]
Hi, are you serious with the development and support of this extension? I like the work you are doing on top of my work. I would like to join forces with you and if I am satisfied with the colaboration, I would unpublish my extension in favour of yours.

Is there something I can do right now?

**Comment by chriscamicas** [comment]
Yes, I am serious.
I have multiple needs around ABL and OpenEdge and I'm trying to solve them with VSCode.
Right now, my priorities are
- Remote debugger (connect to and debug a remote AppServer)
- Unit Test integration (based on ABLUnit)
- Code completion and better language service

I'm open to collaboration, feel free to create pull requests anytime.
What are you needs on your side ?
And by the way, thanks for initiating your extension, it was a kick-starter for me!

**Comment by vsobotka** [comment]
Interesting. We do not use unit tests nor remote debugger, but when this feature gets implemented, I think some of my coworkers could use it.

My priority was to create an extension for me and my coworkers so we are able to write ABL programs in a capable and extensible editor. I also created a task so we are able to run procedures directly in VSCode. So my main priority would be code completion and better language service. I was hoping that with publishing the extension I would get some feedback and feature requests to get me going, but the OE community feels very silent.

Unfortunately we use include files very frequently and there were some caveats. When I have time, I will create some tests for those special use cases so it won't get broken in the future. And then think about other things that could be improved.

Looking forward to collaboration :)

**Comment by chriscamicas** [comment]
Any feedback on how you and your coworkers use OE ABL is a valuable input for me (us).
I also implemented a task at first, and then a command in this extension for local execution.
It's usefull but not enough for us.

We also use include files very frequently, any work around them (parsing ? refactoring ?) is much appreciated.

**Comment by chriscamicas** [comment]
Have you reached the OE community in their forum ?
There's also a fresh new Slack community : openedge.slack.com
you can join right here : https://openedge.slack.com/shared_invite/MTgwODYyODI4MDM2LTE0OTQzMzg3NzctYjg1MTllNjgwNQ
