### ISSUE TITLE
Allow Specifying DLC in Config File

### ISSUE THREAD

**Issue by kihashi** [chriscamicas/vscode-abl#13]
Is there any chance that a feature could be added to allow specifying `DLC` in the config file? Setting it as an environment variable is problematic for me as I need to support multiple OE versions. 

Also, it might be worth mentioning setting the environment variable in the `Using` section of the readme. I had to look at #4 to figure out why syntax checking was not working for me.

**Comment by hechpan** [comment]
I did this a while ago, but didn't continue with it. Not sure if it is still valid.
https://github.com/hechpan/vscode-abl/commit/b70ab44b88e70b90d84a4891ab6e65f764b1e93a

**Comment by chriscamicas** [comment]
Thank you for your contribution.
You are right, the README is missing a prerequisite section. I'll add it soon.
Concerning the multiple OE versions, in your use case, are you projects (or workspaces) associated to one OE version ? I'm guessing you have different project per client/environment using each one and only one different version of OE.
If so, I'm thinking of keeping the global `DLC` envvar as a default/fallback place to look into, and add an optional overwrite in the project settings (ie oe config file).
(very similar to your modification)

Feel free to contribute using a pull request to submit modifications to the current project. Contributions to code and documentation are very welcome :)

**Comment by viitaset** [comment]
Any chance on getting DLC in Config File implemented? envvar is problematic as stated in previous comments.

**Comment by chriscamicas** [comment]
Available in 0.8 (81588d66b7837bb926d0c1db786b7017142a0318)
