### ISSUE TITLE
Debugger Immediately stops without any error.

### ISSUE THREAD

**Issue by wiscow** [chriscamicas/vscode-abl#14]
First off,  

Awesome plugin! 

I am trying to get the remote debugging feature working and i can't seem to get it working properly.  Whenever i hit debug it immediately stops without error.  I am able to debug to the same IP and port using OpenEdge studio.  Any ideas on how i can track down the issue?  Here is a snippet from my launch JSON:
```
        {
            "name": "Attach",
            "type": "abl",
            "request": "attach",
            "port": 3099,
            "address": "172.16.24.70",
            "localRoot": "${workspaceFolder}"
        }
```
Thanks,
Kyle.

**Comment by wiscow** [comment]
Furthermore,  

I attempted to pull the source of your repo and do some debugging on my own (would like to contribute to this as well), but i am not able to hit breakpoints when running the "Extension and Server" debug option. 

My current version of Vs Code is as follows:

Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by chriscamicas** [comment]
Thank you for your report.
To debug an extension (more precisely a debug  adapter) you have to:
- Start the VScode debugger for the extension with `Launch as Server` configuration. It will wait for a network connection on port 4712
- start another vscode on the project you'd like tout debug, modify the launcher.json to add the `debugServer` option with the same port 4712, and launch your debug session as usual

While debugging the second vscode will connect to the first one, which is running the debug extension you'd like to debug.
Obviously breakpoints goes into the first vscode.

Please let me know what you find, I'm happy to have external contribution to this project 😉

**Comment by wiscow** [comment]
That was the missing piece!  the debugger port did the trick i am now debugging.  Ill try to pinpoint the issue.

**Comment by wiscow** [comment]
Ok so here is my intial finding.  Here are the log messages from the debug adapter (I starred out the file path):

SetBreakPointsRequest
send(break B;1;E;C:\******\*******.p;37; ;)
SetBreakPointsResponse
{"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
Connection closed
TerminatedEvent

it looks like the connection is getting terminated after it sends the breakpoint message to the appserver.  
How did you figure this out??  Is there documentation on the protocol somewhere or did you just monitor the traffic? 

are you available for a quick rundown of how this operates? 

This seems like it may be an issue with promise resolution.

Thanks,
Kyle

**Comment by chriscamicas** [comment]
I monitored the network and guessed the protocol.
My understanding is the extension send the breakpoints message and get the response but fails to process the response message.
You can dig in the message handling functions for more details.
I'll be happy to help, be sure to check the vscode extension development documentation, it was very helpful for me.
Concerning the openedge debugger protocol, I should write a detailed documentation on how it operates (or how I understand it works), meanwhile  I can explain if you need to.

**Comment by wiscow** [comment]
Ok through wireshark i am seeing some different communication protocol when running through openedge studio.  Which version of progress do you run against?

**Comment by chriscamicas** [comment]
I tested with 11.6 and 11.7 both x86 and x64.
There are 2 differents debugger protocol, one for the OpenEdge Legacy Debugger, one for PDSOE (Developer Studio, formerly known as Architect). I use exclusively the second one as it has more feature and better message content
What's your OE version ?

**Comment by wiscow** [comment]
We just recently upgraded to 11.7.  However, we are still running the Classic AppServers in a linux environment.  In Open Edge Studio my debugger is setup to remote as an Exteranl AVM (?).  The first connection message that you are sending is much different from the data payload that my OpenEdge Studio debugger is sending to my AppServer.  Forgive me as i am not on my work PC, but i think the initial payload was something like 20 bytes with a `J` somewhere in the middle.

**Comment by chriscamicas** [comment]
Very interesting! I did successfully debugged a 11.7 Classic AppServer in a Windows environment.
I never tried on Linux, I probably should have.
When you say "OpenEdge Studio", you mean Progress Developer Studio for Open Edge ? (The pimped version of Eclipse) don't you ?

**Comment by wiscow** [comment]
Yes the developer studio is what i am using. Maybe i will try that next and see if i get different results connecting to a AppServer on my windows machine (My development environment is windows) using Developer Studio.

**Comment by wiscow** [comment]
Ok So more digging.  I found that through the developer studio debugging session i eventually see messages like the ones you are sending.  It is just that there a are a couple initial handshake messages that i cannot decode.  I have a WireShark snapshot saved that shows this communication.  Is this something you could take a look at?

**Comment by wiscow** [comment]
Ok well i was able to replicate the socket traffic i was seeing by directly injecting them into your code.  However, i hit a roadblock when i received the message "invalid passphrase".  Which makes me think that there is some authentication going on here.  The odd thing is, we do not have authentication turned on for our broker.

**Comment by wiscow** [comment]
Oh my.  I FINALLY got it to work.  I had enabled the broker debugger, which i guess is something completely different... Oh good old progress.  Anyway once i ran the proDebugConfig and ran a debug server on the Linux side i was finally able to connect without code modifications.  For some reason the -debugReady flag on the appserver startup parms was not working properly.  Anyway i think i can move on now :)
