### ISSUE TITLE
Words "not" and "and" are not colour coded like other ABL key words

### ISSUE THREAD

**Issue by Orionsg** [chriscamicas/vscode-abl#16]
E.g. are "where", "if", "do" and "end" colour coded so they are easily distinguishable from variable names.

**Comment by chriscamicas** [comment]
Do you have a code snippet to illustrate the issue and expected behavior ?
Thank you

**Comment by Orionsg** [comment]
Sure, e.g.:

if 5 <> 6 and not 1 <> 2 then.

If  I type in the above code in a procedure, e.g. test.p. the word "if" and "then" are colour coded, whereas "and " and "not" are not.

**Comment by fabiopicolijr** [comment]
@Orionsg I've tested your example and I think you did not understand the ABL editor. The command's "and" and "not" are white and the numbers are light light green. But I have to agree that they are too similar.

@chriscamicas maybe we can improve this changing the color from any of them?

**Comment by Orionsg** [comment]
@fabiopicolijr: 
Sure the numbers could be in another more distinct colour. However, my point is not about the numbers, but the fact that the words "and" and "not" are ABL keywords and so should be colour coded in blue, just like "if" and "then" are in the example code.
If you open my example code in the Progress Open Edge Architect editor, you will see that "if", "and", "not" and "then" are all colour coded in blue, indicating that they are keywords of Open Edge ABL. So they should similarly be coded in the VSCode ABL plugin.
Do you agree?

@chriscamicas: This is, of course, minor details, but might as well be fixed, when an update is planned on this excellent plugin.

**Comment by fabiopicolijr** [comment]
@Orionsg Sorry, now I understand and agree with you 100%. It is a minor detail that maybe could easily fixed. I'm trying to understand how plugin developp works and then, if it is possible, I will help.

**Comment by chriscamicas** [comment]
I chose to treat `and` and `not` as operators, and not keywords, so they behave like `&&` and `!` in JavaScript.
Is this really harder to read in a day to day use ?

Note: with the theme I use (Monokai) keywords and operators uses the same color.

**Comment by chriscamicas** [comment]
According to https://code.visualstudio.com/docs/getstarted/themes you can override your default theme color with the following setting:
```
{
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "keyword.operator",
                "settings": {
                    "foreground": "#0000FF",
                }
            }
        ]
    }
}
```
The `keyword.operator` scope currently targets:
`or` `and` `not` `is` `eq` `ge` `ne` `le` `lt` `gt`
and
`<=` `<`>` `>=` `=` `+` `-` `/` `<` `>` `,`

Hope it will help
