### ISSUE TITLE
Missing Ctrl+p +@ Symbol information

### ISSUE THREAD

**Issue by fabiopicolijr** [chriscamicas/vscode-abl#18]
Ctrl+p +@ Symbol information is a great funcionality that vscode has on other languages. The Symbol list with procedures, functions and variables, for example.

**Comment by chriscamicas** [comment]
This would require a full language understanding and thus a Language Server (grammar, lexer/parser, etc.)
https://code.visualstudio.com/docs/extensions/example-language-server

**Comment by chriscamicas** [comment]
Duplicate with #23
