### ISSUE TITLE
How I can run the app?

### ISSUE THREAD

**Issue by apis3445** [chriscamicas/vscode-abl#2]
Hi! what is the command for check syntax or run the app? I set the launch.json config file but I don't know how check syntax

**Comment by chriscamicas** [comment]
The default shortcut to Check Syntax is Shift+F2 (like in the Progress Procedure Editor)
To run the current file, the shortcut is F2 (also like in the Procedure Editor).

Note you also can run those 2 commands from the VSCode command bar (press F1 to open it, and then type `ABL` to show you all the available commands)

**Comment by apis3445** [comment]
ok thank you

**Comment by chriscamicas** [comment]
you're welcome, and BTW you also have auto check syntax on file save.
If you like this extension, please leave a review on the VSCode marketplace
https://marketplace.visualstudio.com/items?itemName=chriscamicas.openedge-abl
