### ISSUE TITLE
Support for code outline which is now available in VSCode 1.25.1

### ISSUE THREAD

**Issue by Orionsg** [chriscamicas/vscode-abl#20]
There is a new, great feature released in VSCode 1.25.1: Code Outline.

However, I think the OpenEdge ABL Extension needs to support it as right now when you open the Outline Pane (new pane in the same side as and under the File Explorer) for a Open Edge ABL File, it says: "There are no editors open that can provide outline information."

Code outline is one of the few features that I miss from the OpenEdge Architect IDE.

**Comment by chriscamicas** [comment]
Duplicate with #23
