### ISSUE TITLE
Support more Filetypes

### ISSUE THREAD

**Issue by Lordi999** [chriscamicas/vscode-abl#27]
Is there a possibility to add more supported FileTypes like *.xxp,*.xxw,*.cdf ?

**Comment by chriscamicas** [comment]
Hi, what are these files extensions exactly ?
I can't find any documentation

**Comment by Lordi999** [comment]
Oh, my goof. These Files aren't official ABL-Files.

But i just found out, that yout can add them in the settings.json:

```
"files.associations": {
        "*.xxp": "abl",
        "*.xxw": "abl"
    }
```
