### ISSUE TITLE
Syntax highlighting is broken when a function argument is a string containing closing parenthesis

### ISSUE THREAD

**Issue by moceanblur** [chriscamicas/vscode-abl#28]
`replace("123", "1", ")"). message 1.`

Quoted parenthesis is treated as the closing parenthesis for the function call and everything after gets highlighted as a string that doesn't have a closing quote.

![image](https://user-images.githubusercontent.com/26783229/54048668-5002cb80-418f-11e9-9e32-3bb4d8d3bc29.png)

**Comment by chriscamicas** [comment]
thanks for the report
I just saw it today also 😉

**Comment by chriscamicas** [comment]
fixed in 0.7.7
that was easier than expected 😉
