### ISSUE TITLE
How configure propath?

### ISSUE THREAD

**Issue by apis3445** [chriscamicas/vscode-abl#3]
Hi! I create an .openedge.json file in the root folder of my app, I configure the propath 
{
    "proPath": [
        "d:\\docs\\0001fue",
        "d:\\docs\\0184ico"
        
    ],
    "proPathMode": "append", // overwrite, prepend
    "startupProcedure": "d:\\docs\\0184fue\\sis000101a.p",
    "startupProcedureParam": "D:\\docs\\0184lsh\\CATf.ini", // -param
    "parameterFiles": [ // -pf
        "D:\\docs\\0184lsh\\CATf.pf"
    ]
}

but when I try to run the compile doesn't find the files that exists in d:\\docs\\0001fue, when I press the F1 to see the comand of the propath shows the propath only with ...

**Comment by chriscamicas** [comment]
PROPATH in the .openedge.json is actually a WIP.
On the other side, `startupProcedure`, `startupProcedureParam` and `parameterFiles` works fine.
As a workaround, I suggest you hand-modify your PROPATH in your startupProcedure `sis000101a.p`.

I'll keep this issue open until I finalize this feature.

**Comment by chriscamicas** [comment]
version 0.5 of the extension is out and implements the proPath et proPathMode
