### ISSUE TITLE
I need help to configure in order to run simple codes.

### ISSUE THREAD

**Issue by matcs06** [chriscamicas/vscode-abl#38]
Hi @chriscamicas, I appreciate so much you work, but I need some help because I'm currently receiving the following error (Failed to continue "Erro: connect ECONNREFUSED 127.0.0.1:3099"). One thing that is important to know is that I did not change or added any file like propath stuff, so I really need help to set up from the beginning, and here is the .json file where the error appers:

    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach",
            "type": "abl",
            "request": "attach",
            "port": 3099,
            "address": "127.0.0.1",
            "localRoot": "${workspaceFolder}"
        }
    ]
}

I dont know what i need to change or if i need to add any file like this one (.openedge.json) that you have put in the description, if i need, the folder to this one (.openedge.json)  is the same as the .p file that I'am working? And what I would need to change in this file too.

**Comment by diegoclair** [comment]
I have the same problem, I put   `"request": "lauch"` with out port and address, only with `"program": ${workspaceFolder}` and I'm receiving the same error (Failed to continue "Erro: connect ECONNREFUSED 127.0.0.1:3099").
I saw the log and there said about 'length' (renderer1] [error] Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined at ReadFileContext.callback)
I put the var `err` to show in console.log but it was empty.

**Comment by chriscamicas** [comment]
Hi, the `launch.json` configuration is only useful for debugging purpose.
If you just want to execute a p-file, you can simply run the `ABL: Run` command.
By default, the keyboard shortcut is `F2`

**Comment by chriscamicas** [comment]
I created the issue #39 to simplify the debugging experience and it's actually available in the dev branch.

**Comment by diegoclair** [comment]
Thank you @chriscamicas !
Now, when I'm executing the code, show me the following error: (error: error=Error: spawn C:\dlc116\bin\_progres ENOENT)

I saw the issue (https://github.com/chriscamicas/vscode-abl/issues/4) but only with env var it doesn't work.

![image](https://user-images.githubusercontent.com/35784268/57698547-3d43c180-762c-11e9-8aa5-3c68bc15b17a.png)

**Comment by chriscamicas** [comment]
when you change an environment variable for the system, you have to restart your local session (logoff, login)
otherwise you can create the same variable for your user (top part of the window) and you'd only need to restart vscode.

**Comment by diegoclair** [comment]
@chriscamicas Thank you!! 
I restart my machine, but the problem continue:

![image](https://user-images.githubusercontent.com/35784268/57699888-2a7ebc00-762f-11e9-84fe-4ae2635c19f2.png)

![image](https://user-images.githubusercontent.com/35784268/57699822-04591c00-762f-11e9-83f8-e33bd1805301.png)

![image](https://user-images.githubusercontent.com/35784268/57699917-3ec2b900-762f-11e9-8646-cf4d170930f4.png)

**Comment by chriscamicas** [comment]
can you try to run `%DLC%\bin\_progres` in a windows command line please ?

**Comment by diegoclair** [comment]
Yes, sure:

![image](https://user-images.githubusercontent.com/35784268/57700553-a0375780-7630-11e9-9f4c-bcf2fefe4aeb.png)

![image](https://user-images.githubusercontent.com/35784268/57700567-a4637500-7630-11e9-8c1f-45fb6b113a90.png)

**Comment by chriscamicas** [comment]
well that's weird ...
May be a file access security issue, what are you user rights on the file ?
_progres > right click > properties > security tab ?

**Comment by diegoclair** [comment]
![image](https://user-images.githubusercontent.com/35784268/57701456-6bc49b00-7632-11e9-9c8a-6104d9bdc4d7.png)

**Comment by chriscamicas** [comment]
No clue, may be you can try debugging the extension on your machine.
You could clone this repo and build the extension locally.

**Comment by matcs06** [comment]
Hi @chriscamicas,
Thanks so much! I just needed to add the DLC system variable that you mentioned in issue (#4 ), it is working now:
![image](https://user-images.githubusercontent.com/38388657/57701798-1e94f900-7633-11e9-901f-e52347a4e76e.png)


Here is how it is in windows 10 

![image](https://user-images.githubusercontent.com/38388657/57701920-5d2ab380-7633-11e9-929a-6980358c24e0.png)

Thank you so much again!

**Comment by diegoclair** [comment]
For me, maybe can be something about security :( ..
My vscode is installed in my user.

**Comment by chriscamicas** [comment]
So is mine

**Comment by matcs06** [comment]
The only problem remaining here is that I could not update the variable, it shows this message.

![image](https://user-images.githubusercontent.com/38388657/57702918-6157d080-7635-11e9-978f-09ffd82f9318.png)

**Comment by chriscamicas** [comment]
the extension execute the p-file  in batch mode `-b`, so these statements are not working.
you need an interactive window to be able to use update/display.

the batch mode is needed to be able to redirect stdout in the output pane of VSCode.
Currently it does not support external execution. The best workaround I can think of, could be to execute in an external terminal the following command:
`%DLC%\bin\_progres -p your_file.p`

**Comment by diegoclair** [comment]
@chriscamicas Thank you so much for your help.
My problem was relationeted with the security, so I sign in in my machine as administrator and install the extension, so it's worked.

I saw yout last response about display, so sad, but I think that we are in the right way with your extension, perhaps in the future we'll can do this.

Now, I have a question about Check Syntax, what can I do to work? Can you help me?
![image](https://user-images.githubusercontent.com/35784268/57707530-2d34dd80-763e-11e9-803b-19074c955987.png)

And the last one, would be how can connect with my database with my own tables?

**Comment by chriscamicas** [comment]
you need an `.openedge.json` file (properly configured) for both to work

**Comment by diegoclair** [comment]
@chriscamicas 
I have search since yesterday how can I configure the file `.openedge.json`, you can help me with link or something? If will necessary, I can open a new issue here.

**Comment by chriscamicas** [comment]
BTW you can enable an interactive mode using VSCode tasks, here is an example:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "ABL interactive",
            "type": "process",
            "command": "c:\\Progress\\OpenEdge\\bin\\_progres.exe",
            "args": [
                "-p",
                "test.p"
            ],
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": true,
                "panel": "shared",
                "showReuseMessage": false,
                "clear": false
            },
            "options": {
                "cwd": "${workspaceRoot}"
            },
            "problemMatcher": []
        }
    ]
}
```

**Comment by diegoclair** [comment]
@chriscamicas 
Thank you so much.

**Comment by diegoclair** [comment]
Where I need to put the file `.openedge.json` ? Because I'm put in my workSpaceFolder and I have this example inthe file:
![image](https://user-images.githubusercontent.com/35784268/57721932-c7574e80-765b-11e9-8dba-a3ff78baa77c.png)

So I try this code:
![image](https://user-images.githubusercontent.com/35784268/57721982-df2ed280-765b-11e9-8299-609edc6eb7d0.png)

I have the file there:
![image](https://user-images.githubusercontent.com/35784268/57722009-f077df00-765b-11e9-809a-b1b366ddbf76.png)

If I put the file in my WorkSpaceFolder:
![image](https://user-images.githubusercontent.com/35784268/57722150-3df44c00-765c-11e9-8382-4eaad92745f4.png)

So the code find the file:
![image](https://user-images.githubusercontent.com/35784268/57722311-83187e00-765c-11e9-91cd-934c6eeae352.png)

Now, I think that I don't know where I need to put the file or why its not working.
