### ISSUE TITLE
Error when I try to run the syntax checking.

### ISSUE THREAD

**Issue by Animaniac** [chriscamicas/vscode-abl#4]
Hi thanks for this its great. However when I try to run the syntax checking I get the following error:

"Running the contributed command:'abl.run.currentFile' failed."

No indication of why, any help is appreciated.

**Comment by chriscamicas** [comment]
Do you have Progress OpenEdge installed on your machine ? if so which version ? and what OS do you use ?

**Comment by Animaniac** [comment]
running openedge 10.1b with windows 7

**Comment by chriscamicas** [comment]
Have you set your DLC env var ?

**Comment by Animaniac** [comment]
No, how would I go about doing that?

**Comment by chriscamicas** [comment]
You'd have to follow this tutorial https://www.nextofwindows.com/how-to-addedit-environment-variables-in-windows-7
And set up a variable named DLC with a value pointing to your openedge install dir
My set up is:
![image](https://user-images.githubusercontent.com/7702519/30153018-65704e22-93b5-11e7-8065-37ecc78c48e9.png)

**Comment by Animaniac** [comment]
The only installation I can find on the machine is a shared network one, pointed the path to that but get this:

error: error=Error: spawn C:\Program Files (x86)\Progress Software Corporation\OpenEdge 10.1B Shared Network Installation\bin\_progres ENOENT

**Comment by chriscamicas** [comment]
where is your `_progres.exe` located ?

**Comment by chriscamicas** [comment]
@Animaniac I close this issue since there was no reply for a long time.
I consider it a configuration issue.
