### ISSUE TITLE
"Syntax OK" stays visible after opening new file that has not been checked

### ISSUE THREAD

**Issue by cverbiest** [chriscamicas/vscode-abl#40]
I'm not sure if this is a vscode issue or a vscode-abl issue.

To reproduce

- open an ABL source that compiles
- check syntax, that status should now show "Syntax OK"
- open an ABL source that fails to compile
- the "Syntax OK" is still shown on the status bar

**Comment by chriscamicas** [comment]
Thank you for your report, it was indeed quite confusing.
It's now fixed in v1.1.1
