### ISSUE TITLE
Syntax Highlighting - Include files passing strings containing braces

### ISSUE THREAD

**Issue by mar-kelly** [chriscamicas/vscode-abl#45]
Syntax highlighting will fail if a closing brace is passed in a string to an include file:
{ test.i "}" }
Our use case is when we pass a preprocessor like so:
{ test.i "{&Test}" }

When dealing with braces it seems to always link the first open brace to the first closing brace regardless of content.

Thanks In Advance

**Comment by chriscamicas** [comment]
Thanks for the report, the fix is available in extension v1.1.3
