### ISSUE TITLE
.t (database trigger file is not available to be edited)

### ISSUE THREAD

**Issue by allanbsoliveira1987** [chriscamicas/vscode-abl#46]
Hello there,
When I try to open a file .t unfortunatelly it is not consider as programing progress abl file.
.t files is very used and should be considered on the open list.

Another doubt I have is regarding the keywords... the vistual studio code highlight the keywords but there is no pop-up with a list containg them... it would very desired to type "def" and appear in the editor a pop-up list with "define".

gracias.

**Comment by chriscamicas** [comment]
Thank you for your submission.
I'm not quite sure `.t` is an official extension, do you have the reference to the documentation for that ?

Anyway, you can still had it yourself to your vscode workspace settings, using the following values:
```
  "files.associations": {
    "*.t": "abl"
  }
```

Noted for the keyword completion, it's actually on the backlog

**Comment by chriscamicas** [comment]
Closing this issue since there is no official documentation reference
