### ISSUE TITLE
Support for Remote-SSH?

### ISSUE THREAD

**Issue by putin266** [chriscamicas/vscode-abl#47]
I'm used to working on mac, but there is no progress version for mac. While I have an linux server that has the whole environment settings, then I tried to use the remote-ssh and this extension. Some error appears when saving the source code:

Error: Unable to open or create undefined/lbi8B76Dv, error 2. (354)

It seems the extension is creating a temp file for compile, but somehow it fails. It would be great if the extension could support the remote development.

**Comment by putin266** [comment]
I've created a pull request that could fix this. Please kindly review it. Thanks.

**Comment by chriscamicas** [comment]
fix available in v1.1.6 just published
