### ISSUE TITLE
Move from tslint to eslint

### ISSUE THREAD

**Issue by chriscamicas** [chriscamicas/vscode-abl#52]
tslint will be deprecated anytime soon
https://github.com/palantir/tslint/issues/4904

We should move to eslint

**Comment by RobinHerbots** [comment]
See https://github.com/chriscamicas/vscode-abl/pull/51/commits/08dec56e9fabfb2de6295dd0064e63f8ed4d5f2c

I added the wrong issue number in the commit 👎   #55 => #52

**Comment by gquerret** [comment]
Changes in commit f729aef
