### ISSUE TITLE
Syntax problem

### ISSUE THREAD

**Issue by jousmo** [chriscamicas/vscode-abl#6]
Look what happens to the syntax when using a dot within a definition in the LABEL

1.- VSCODE 1.16.1
2.- OpenEdge ABL 0.6.2
3.- Theme: Cobalt2 (WesBos) 2.1.3
4.- [test.p.zip](https://github.com/chriscamicas/vscode-abl/files/1306540/test.p.zip)

<img width="748" alt="captura de pantalla 2017-09-15 a la s 08 51 14" src="https://user-images.githubusercontent.com/7170689/30485697-d8d665ba-99f3-11e7-838d-87faab748393.png">

**Comment by chriscamicas** [comment]
Great one, I made a wrong assumption 
```JSON
      "comment": "Let's assume define can't have '.' inside",
      "name": "meta.define.abl",
```
Thanks for the detailed example, I'll look into it
