### ISSUE TITLE
Getting Error Unable to open parameter file, error 2.  (1247) on parameter file

### ISSUE THREAD

**Issue by pdreslin** [chriscamicas/vscode-abl#63]
I'm trying to setup VS code with the extension and have my configuration file defined like this:
{
    "workingDirectory": "${workspaceFolder}/work",
    "proPath": [
        "C:\\Temp\\developerModel\\new2\\dm",
        "${workspaceFolder}"
    ],
    "dlc": "C:/Progress/OpenEdge", 
    "proPathMode": "append", 
    "parameterFiles": [ "C:\\Temp\\developerModel\\new2\\dmdefault.pf"
    ],
    "startupProcedure" : "",
    "dbDictionary": [
        "myDatabaseForAutoComplete"
    ],
    "format": {
        "trim": "right"
    }
}

The dmdefault.pf only has the -1 parameter in it.

Any help is greatly appreciated.

**Comment by pdreslin** [comment]
I've got it working now - not sure what happened - but I was using the whole path to the file and it may not have liked the escaping or something.  Just used the relative path and it worked.

**Comment by chriscamicas** [comment]
You should probably escape the backslashes in your path string: 
`"parameterFiles": [ "C:\Temp\developerModel\new2\dmdefault.pf"`

`"parameterFiles": [ "C:\\Temp\\developerModel\\new2\\dmdefault.pf"`
otherwise, it might be interpreted as a special char `\t` is the code for tabulation.
