### ISSUE TITLE
Extension not showing up in https://open-vsx.org/

### ISSUE THREAD

**Issue by asthomasdk** [chriscamicas/vscode-abl#69]
I am testing out a new environment using Gitpod (gitpod.io) which uses VS Code in containers and a browser. Part of the plan is to make this work with my own OpenEdge containers so that we can do OpenEdge development from there, 

But - the extension does not show in https://open-vsx.org/, which is where all of the supported extensions are sourced from. 

I believe there are some updated requirements for enabling extensions there that need to be met. Is there any chance that this can be done so we can try it out?

**Comment by chriscamicas** [comment]
Hi Thomas, thanks for the message, I'm glad you're using this extension.
From my understanding, open-vsx is a FOSS alternative to VSCode Extensions Marketplace.
For an extension to be available in open-vsx, you need to specifically publish targetting this registry.
cf https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension

The submission process is very similar to what Microsoft/VSCode Marketplace is already doing.
So it's seems feasible.
I can try a manual submission to start with, and if your tests are positive, we can think of an automatic deployment.

**Comment by asthomasdk** [comment]
Excellent! 

 

I am working on a project where there is some good interest in being able to do OpenEdge development from VS Code in a browser – and therefore in your extension. So any help you can provide is very much appreciated. 

 

Regards

Thomas Hansen
___________________________________
***@***.*** ***@***.***> 

 <https://www.nodeable.io/> 
secureable <https://www.nodeable.io/secureable> : a secure, multi authentication backend and acl permissions platform for OpenEdge applications

**Comment by chriscamicas** [comment]
Very interesting, VSCode and Github are also into something like this : https://code.visualstudio.com/docs/remote/codespaces

**Comment by asthomasdk** [comment]
Yup – I have also been looking at this. Been waiting for ages for access to the beta which has been going on a for a long time now. 


There used to be a version of codespaces on Azure as well – but MS decided to merge it all into the Github version. 

 

Regards

Thomas Hansen
___________________________________
***@***.*** ***@***.***> 

 <https://www.nodeable.io/> 
secureable <https://www.nodeable.io/secureable> : a secure, multi authentication backend and acl permissions platform for OpenEdge applications

**Comment by chriscamicas** [comment]
hey @asthomasdk I just published a dev version of the extension in open-vsx
https://open-vsx.org/extension/chriscamicas/openedge-abl

please let me know if it works for you

**Comment by asthomasdk** [comment]
Thanks! 

I get this warning when I click on your link: 
![image](https://user-images.githubusercontent.com/7262873/118776105-e8c12580-b887-11eb-8bfb-60f78277ab78.png)

But ... it seems to work. 

![image](https://user-images.githubusercontent.com/7262873/118776190-01c9d680-b888-11eb-9687-53a928524f28.png)

Will try and get it working as well and see how it goes. 

Thanks so much for the help!

**Comment by chriscamicas** [comment]
the warning is being taking care of
https://github.com/EclipseFdn/open-vsx.org/issues/513
claiming a namespace is manual ...

**Comment by asthomasdk** [comment]
Looks like I can get the extension installed and running inside Gitpod. Now to see if it all works ;-)
