### ISSUE TITLE
Check Syntax, Debugger, Run in OS X

### ISSUE THREAD

**Issue by jousmo** [chriscamicas/vscode-abl#7]
![captura de pantalla 2017-09-15 a la s 11 17 00](https://user-images.githubusercontent.com/7170689/30493263-10b76410-9a09-11e7-94b1-70594f2894b8.png)

Hi, we had a pending conversation. in OS X there are no binaries of Progress OpenEdge, I wondered if it could work if the binaries were on a remote computer.

**Comment by chriscamicas** [comment]
Check syntax, and execution is currently not workable on OS X. Remote execution, would require some sort of client/server architecture and the only compatible component available from Progress to do so is the [OpenClient](https://documentation.progress.com/output/ua/OpenEdge_latest/index.html#page/dvjav%2Fpurpose.html%23) library for Java. It would also require a server component (like the classic AppServer from Progress).
Could you describe your whole environment please ? (what you use progress for, which components, etc).

By the way, the debugger should work just fine, this component is entirely written in TypeScript (from the ground up)

**Comment by chriscamicas** [comment]
Remote execution is not on the roadmap
sorry
