### ISSUE TITLE
Changing ABL editor key bindings

### ISSUE THREAD

**Issue by ntreeby** [chriscamicas/vscode-abl#78]
How do I change the ABL editor key bindings for syntax checking from the default Shift-F2? I can turn off the key bindings altogether, but that's not what I want.

My problem is that I am running via Citrix, and Citrix is set to intercept Shift+F2 and minimizes my desktop, instead of passing it through to the application.  So, I'd like to re-map the syntax check to a different key binding.  I'm not the Citrix admin, so I don't have the ability to stop Citrix from intercepting Shift+F2.

**Comment by gquerret** [comment]
Press Ctrl + Shift + P, then type Keyboard Shortcuts. You'll see this kind of list:
![image](https://user-images.githubusercontent.com/6498723/151056753-8ec898e8-2bc5-4d6d-bc42-983b248591f6.png)
Then double-click on existing shortcut, and type a new one.

Some reference here: https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization

**Comment by viitaset** [comment]
I would suggest that you just save the file (CTRL + S), it will check syntax.
