### ISSUE TITLE
Comments in .p files OpenEdge 10.2A

### ISSUE THREAD

**Issue by Vehlin** [chriscamicas/vscode-abl#8]
OE versions prior to 11.6 don't support single line comments in .p files. Any chance you could change them to /* and */ comments instead?

**Comment by chriscamicas** [comment]
You mean when you hit `Ctrl+/` you'd like /* and */ instead of // ?

**Comment by chriscamicas** [comment]
Have you tried `Shit+Alt+A` (it's the toggle block comment shortcut) ?

**Comment by Vehlin** [comment]
No. Your .p files contain // comments that older versions can't run. I had
to edit them out to get syntax highlighting etc to run

On 9 Oct 2017 15:57, "chriscamicas" <notifications@github.com> wrote:

Have you tried Shit+Alt+A (it's the toggle block comment shortcut) ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chriscamicas/vscode-abl/issues/8#issuecomment-335183819>,
or mute the thread

**Comment by chriscamicas** [comment]
oh right! my bad... will change them ASAP

**Comment by chriscamicas** [comment]
feel free to fork and create a PR next time
