### ISSUE TITLE
syntax highlight

### ISSUE THREAD

**Issue by jruzicka-hk** [chriscamicas/vscode-abl#9]
Hi, I have problem with syntax highlight when I write text with period inside apostrophes (e.g. 'Test.label'). When I use quotation marks, it is ok  (e.g. "Test.label").
![obrazek](https://user-images.githubusercontent.com/33261784/32236223-e143839e-be61-11e7-9d3a-37a8689bbb6c.png)

**Comment by chriscamicas** [comment]
thanks for reporting this issue.
As a workaround, you can replace the single quoted string by a double quoted string.
